# Generated by Django 5.1.2 on 2024-11-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_perfil'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Perfil',
        ),
    ]
