# Generated by Django 5.1.2 on 2024-11-27 03:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta1', models.IntegerField()),
                ('pregunta2', models.IntegerField()),
                ('pregunta3', models.IntegerField()),
                ('pregunta4', models.IntegerField()),
                ('pregunta5', models.IntegerField()),
                ('pregunta6', models.IntegerField()),
                ('pregunta7', models.IntegerField()),
                ('pregunta8', models.IntegerField()),
                ('resultado', models.CharField(default='INDETERMINADO', max_length=50)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(default='INDETERMINADO', on_delete=django.db.models.deletion.CASCADE, related_name='Respuesta', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
